openapi: 3.0.1
info:
  title: Hangar Transfer Format
  description: |
    This is a draft specification for a file format which will facilitate the transfer of hangar data between different community managed tools
  version: 0.0.1
servers:
- url: https://erkul.games
  description: "#DPSCalculator"
- url: https://api.fleetyards.net
  description: "API for RSI data"
- url: https://hangarxplor.space
  description: "Browser plugin to manage your RSI hangar"
- url: https://www.starship42.com
  description: "Star Citizen ship viewer and more"
- url: https://docs.starcitizen.fans
  description: "Open Specification for Star Citizen community tools"
tags:
- name: erkul.games
  description: "#DPSCalculator for Star Citizen"
  externalDocs:
    description: Find out more
    url: https://erkul.games
- name: FleetYards.net
  externalDocs:
    description: Find out more
    url: https://api.fleetyards.net/v1
- name: HangarXPLOR
  description: Browser plugin to manage your RSI hangar
  externalDocs:
    description: Find out more
    url: https://hangarxplor.space
- name: StarShip42.com
  description: Star Citizen ship viewer and more
  externalDocs:
    description: Find out more
    url: https://www.starship42.com/
- name: starcitizen.fans
  description: Open Specifications for Star Citizen community tools
paths:
  /fleetview/load:
    post:
      tags:
      - StarShip42.com
      summary: Display 3D models of all the ships in your hangar
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                oneOf:
                  - $ref: "#/components/schemas/starship42.ship.json"
      responses:
        200:
          description: successful operation
  /ship-codes.json:
    get:
      tags:
      - starcitizen.fans
      summary: Return a list of all currently supported ships and their associated codes
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/rsi.ship.json"
  /download-json:
    get:
      tags:
      - HangarXPLOR
      summary: Downloads the contents of your hangar from the RSI website
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: "#/components/schemas/hangarxplor.ship.json"
                    
  /erkul:
    get:
      tags:
      - erkul.games
      summary: Reserved for future use
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: "#/components/schemas/erkul.ship.json"
                    
components:
  schemas:
  
    # The bare minimum needed to identify an entity
    core.entity.json:
      properties:
        # (Required) The name of the entity being described
        name:
          type: string
          example: Carrack
        # (Optional) Specifies what type of entity is being described
        entity_type:
          type: string
          example: ship
          default: ship
          enum:
          - ship
          - component
          - decoration
  
    # Core attributes of a pledge as defined by CIG
    rsi.pledge.json:
      properties:
        pledge_id:
          type: string
          example: "12345678"
        pledge_name:
          type: string
          example: "Standalone Ship - Anvil Carrack Warbond - LTI"
        pledge_date:
          type: string
          format: date
          example: "2016-12-08"
        pledge_cost:
          type: string
          format: currency
          example: "$350 USD"
    
    # Core attributes of a ship as defined by CIG
    rsi.ship.json:
      type: object
      properties:
        ship_code:
          type: string
          description: A code that uniquely identifies the ship and it's variant to all community tools
          example: ANVL_Carrack
        ship_name:
          type: string
          description: The name, or nickname of the given ship
          example: Serenity
        manufacturer_code:
          type: string
          description: A code that uniquely identifies the manufacturer to all community tools
          example: ANVL
          enum:
          - AEGI
          - ANVL
          - AOPO
          - ARGO
          - BANU
          - CNOU
          - CRUS
          - DRAK
          - ESPR
          - GRIN
          - KRIN
          - MISC
          - ORIG
          - RSI
          - TUMB
          - VNCL
          - XIAN
        manufacturer_name:
          type: string
          description: The full display name of the ships manufacturer
          example: Anvil Aerospace
          enum:
          - Aegis Dynamics
          - Anvil Aerospace
          - Aopoa
          - Argo Astronautics
          - Banu
          - Consolidated Outland
          - Crusader Industries
          - Drake Planetary
          - Esperia
          - Greycat Industries
          - Kruger Intergalactic
          - Musashi Industrial and Starflight Concern
          - Origin Jumpworks
          - Roberts Space Industries
          - Tumbril Land Systems
          - Vanduul
          - Xi'an
    
    # Definition of a ship as used by erkul.games
    erkul.ship.json:
      allOf:
        - $ref: '#/components/schemas/core.entity.json'
        # Extra fields that erkul.games adds - ideally this list is kept to a minimum
        - type: object
          properties:
            localName:
              type: string
              example: ANVL_Carrack
    
    # Definition of a ship as exported by HangarXPLOR
    hangarxplor.ship.json:
      allOf:
        # It is recommended all community tools support core.entity.json
        - $ref: '#/components/schemas/core.entity.json'
        # Information extracted from the RSI website
        - $ref: '#/components/schemas/rsi.pledge.json'
        # Information about a given ship
        - $ref: '#/components/schemas/rsi.ship.json'
        # Extra fields that HangarXPLOR adds
        - type: object
          properties:
            lti:
              type: boolean
              example: true
            warbond:
              type: boolean
              example: true
    
    # Definition of a ship as imported by StarShip42.com
    starship42.ship.json:
      required:
        - name
      allOf:
        - $ref: '#/components/schemas/core.entity.json'
      
