# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - ship-codes.json
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: franzdiebold/github-env-vars-action@v2.1.0
    - name: Notify
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          description: |
            https://starcitizen.fans/ship-codes.json was updated
            
            **Author**: ${{ env.CI_ACTOR	}}
            **Commit**: [${{ env.CI_SHA_SHORT }}](${{ github.event.head_commit.url }})
            
            ${{ github.event.head_commit.message }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
